CREATE TABLE IF NOT EXISTS llx_completioncertificate (
 rowid integer AUTO_INCREMENT PRIMARY KEY,
 entity integer NOT NULL DEFAULT 1,
 ref varchar(30) NOT NULL,
 fk_soc integer NOT NULL,
 fk_commande integer NOT NULL,
 date_completion date NOT NULL,
 completion_mode smallint NOT NULL DEFAULT 0,
 progress_percent double(24,8) NOT NULL DEFAULT 0,
 order_total_ht double(24,8) NOT NULL DEFAULT 0,
 total_ht double(24,8) NOT NULL DEFAULT 0,
 currency_code varchar(3),
 issue_text varchar(255),
 note_public text,
 status smallint NOT NULL DEFAULT 0,
 fk_user_author integer,
 fk_user_valid integer,
 datec datetime NOT NULL,
 tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uk_completioncertificate_ref_entity (ref, entity),
 INDEX idx_completioncertificate_order (fk_commande),
 INDEX idx_completioncertificate_soc (fk_soc)
) ENGINE=innodb;
